version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: parkfinder_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    env_file:
      - .env
    networks:
      - parkfinder_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./Frontend
    container_name: parkfinder_frontend
    ports:
      - "8081:8081"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # Esta es la clave de bóveda: Obliga a Expo a usar tu IP real
      - REACT_NATIVE_PACKAGER_HOSTNAME=${MY_LOCAL_IP}
    stdin_open: true
    tty: true
    networks:
      - parkfinder_net

  anpr:
    build: ./LicensePlates-ANPR
    container_name: parkfinder_anpr
    ports:
      - "8501:8501"
      - "8001:8001"
    volumes:
      - ./LicensePlates-ANPR:/app
    env_file:
      - .env
#    devices:
#      - /dev/video0:/dev/video0
    networks:
      - parkfinder_net

networks:
  parkfinder_net:
    driver: bridge
