describe("driver", () => {
  it("tests driver", () => {
    cy.visit('/');
    cy.clearCookies();
    cy.clearLocalStorage();
    cy.viewport(1059, 911);
    cy.visit("http://localhost:8081/");
    cy.wait(1000);
    cy.get('input[placeholder="Email Address"]').type("driver@driver.com");
    cy.wait(1000);
    cy.get('input[placeholder="Password"]').type("12345678");
    cy.wait(1000);
    cy.contains("Log In").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(4) > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(1) > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(1) input").click();
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(1) input").type("Leonardoooo");
    cy.wait(1000);
    cy.get("div.r-marginTop-1x0uki6 > div:nth-of-type(1) div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(1) input").click();
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(1) input").type("Leonardo");
    cy.wait(1000);
    cy.get("div.r-color-n2d3oy").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-marginTop-1x0uki6 > div:nth-of-type(2) > div.r-alignItems-1awozwy > div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1oox17p").click();
    cy.get("div.r-backgroundColor-1oox17p > input").click();
    cy.get("div.r-backgroundColor-1oox17p > input").type("AAA999");
    cy.get("div.r-backgroundColor-1cuuowz > input").click();
    cy.get("div.r-backgroundColor-1cuuowz > input").type("TEST");
    cy.wait(1000);
    cy.get("div:nth-of-type(2) > div.r-backgroundColor-1cuuowz > div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("#root > div > div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div.r-borderBottomLeftRadius-tjts8u div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(2)").click();
    cy.wait(1000);
    cy.get("div:nth-of-type(5) div.r-justifyContent-1wtj0ep > div.r-maxWidth-dnmrzs").click();
    cy.wait(1000);
    cy.get("div.r-WebkitOverflowScrolling-150rngu > div > div.r-WebkitOverflowScrolling-150rngu > div > div:nth-of-type(5) > div.css-view-g5y9jx").click();
    cy.wait(1000);
    cy.get("div.r-color-n2d3oy").click();
    cy.wait(1000);
    cy.get("#root > div > div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("#root > div > div.css-view-g5y9jx > div > div > div > div > div > div > div > div.r-alignItems-1awozwy > div.r-transitionProperty-1i6wzkk > div").click({ force: true });
    cy.wait(1000);
    cy.get("div.r-color-1h2of7f").click();
    cy.wait(1000);
  });
});
