describe("park", () => {
  it("tests park", () => {
    cy.visit('/');
    cy.clearCookies();
    cy.clearLocalStorage();
    cy.viewport(1059, 911);
    cy.visit("http://localhost:8081/");
    cy.wait(1000);
    cy.get('input[placeholder="Email Address"]').type("park@park.com");
    cy.wait(1000);
    cy.get('input[placeholder="Password"]').type("12345678");
    cy.wait(1000);
    cy.contains("Log In").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(5)").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(2) input").click();
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(2) input").type("parkingggg");
    cy.get("div:nth-of-type(3) input").click();
    cy.get("div:nth-of-type(3) input").type("351269878");
    cy.wait(1000);
    cy.get("div.r-marginBottom-1yflyrw div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(2) input").click();
    cy.get("div.r-backgroundColor-1cuuowz > div:nth-of-type(2) input").type("parking");
    cy.wait(1000);
    cy.get("div.r-color-n2d3oy").click();
    cy.wait(1000);
    cy.get("div.r-alignItems-1awozwy > div > div.css-view-g5y9jx > div > div").click();
    cy.wait(1000);
    cy.get("div.r-borderBottomLeftRadius-tjts8u div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(3)").click();
    cy.wait(1000);
    cy.get("div.r-marginBottom-15d164r div:nth-of-type(2) > div.r-color-jwli3a").click();
    cy.wait(1000);
    cy.get("div:nth-of-type(2) > div > div > div > div.r-alignItems-1awozwy > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(4) > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div:nth-of-type(2) > div.r-color-1vhg72y").click();
    cy.wait(1000);
    cy.get("input").click();
    cy.get("input").type("AAA999");
    cy.wait(1000);
    cy.get("div.r-boxShadow-1w4hacz > div").click();
    cy.wait(1000);
    cy.get("div.r-boxShadow-1w4hacz > div").click();
    cy.wait(1000);
    cy.get("div:nth-of-type(2) > div > div > div > div.r-alignItems-1awozwy > div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-flexWrap-1w6e6rj > div:nth-of-type(3)").click();
    cy.wait(1000);
    cy.get("div.r-marginBottom-15d164r div:nth-of-type(2) > div.r-color-jwli3a").click();
    cy.wait(1000);
    cy.get("div:nth-of-type(2) > div > div > div > div.r-alignItems-1awozwy > div.css-view-g5y9jx > div").click();
    cy.wait(1000);
    cy.get("div.r-marginTop-1wzrnnt > div.r-transitionProperty-1i6wzkk > div").click();
    cy.wait(1000);
    cy.get("div.r-marginTop-1x0uki6 > div.r-transitionProperty-1i6wzkk").click();
    cy.wait(1000);
  });
});
